@startuml
title DSS - Enviar Conteudo pelo Chatbot

participant Sistema
participant "RepositorioPreferencias" as Repo
participant Chatbot
actor Cidadão

Sistema -> Repo : buscarDestinatariosOptIn()
Repo --> Sistema : listaDeCidadaos
Sistema -> Chatbot : enviarConteudo(destinatarios, noticiaProjeto)
Chatbot --> Cidadão : exibirConteudo()
@enduml
