@startuml
title Diagrama de Sequência do Sistema (DSS) - 3. Cadastrar Instituição

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 3. Cadastrar Instituição
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml