@startuml
title Diagrama de Sequência do Sistema (DSS) - 30. Atribuir Responsável

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 30. Atribuir Responsável
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml