@startuml
title Diagrama de Sequência do Sistema (DSS) - 32. Definir Prazo

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 32. Definir Prazo
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml