@startuml
title Diagrama de Sequência do Sistema (DSS) - 16. Consultar Projetos

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 16. Consultar Projetos
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml