@startuml
title Diagrama de Sequência do Sistema (DSS) - 8. Consultar Cidades

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 8. Consultar Cidades
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml