@startuml
title Diagrama de Sequência do Sistema (DSS) - 31. Registrar Pessoa Atendida

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 31. Registrar Pessoa Atendida
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml