@startuml
title Diagrama de Sequência do Sistema (DSS) - 23. Gerar Relatório por Cidade

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 23. Gerar Relatório por Cidade
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml