@startuml
title Diagrama de Sequência do Sistema (DSS) - 18. Atualizar Status dos Projetos de Lei

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 18. Atualizar Status dos Projetos de Lei
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml