@startuml
title Diagrama de Sequência do Sistema (DSS) - 21. Cadastrar Emenda

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 21. Cadastrar Emenda
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml