@startuml
title Diagrama de Sequência do Sistema (DSS) - 9. Cadastrar Igreja

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 9. Cadastrar Igreja
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml