@startuml
title Diagrama de Sequência do Sistema (DSS) - 25. Visualizar Gráficos

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 25. Visualizar Gráficos
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml