@startuml
title Diagrama de Sequência do Sistema (DSS) - 5. Cadastrar Liderança

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 5. Cadastrar Liderança
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml