@startuml
title Diagrama de Sequência do Sistema (DSS) - 35. Criar Alerta/Lembrete

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 35. Criar Alerta/Lembrete
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml