@startuml
title Diagrama de Sequência do Sistema (DSS) - 29. Consultar Demandas

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 29. Consultar Demandas
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml