@startuml
title Diagrama de Sequência do Sistema (DSS) - 7. Cadastrar Informações da Cidade

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 7. Cadastrar Informações da Cidade
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml