@startuml
title Diagrama de Sequência do Sistema (DSS) - 20. Gerar Relatório de Projetos

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 20. Gerar Relatório de Projetos
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml