@startuml
title Diagrama de Sequência do Sistema (DSS) - 27. Anexar Ofício

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 27. Anexar Ofício
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml