@startuml
title Diagrama de Sequência do Sistema (DSS) - 13. Atualizar Missão

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 13. Atualizar Missão
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml