@startuml
title Diagrama de Sequência do Sistema (DSS) - 24. Gerar Relatório por Área

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 24. Gerar Relatório por Área
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml