@startuml
title Diagrama de Sequência do Sistema (DSS) - 36. Gerar Relatório Consolidado

actor "Ator Principal" as actor
participant ":Sistema" as system

actor -> system: 36. Gerar Relatório Consolidado
activate system

system --> actor: Resposta do Sistema
deactivate system

@enduml