@startuml
actor Usuario

boundary Frontend as FE
control DemandaController as C
control DemandaService as S
entity CidadeModel as City
entity InstituicaoModel as Inst
entity DemandaModel as M
control AuthorizationService as AuthZ
control ValidationService as Val
control HistoryService as Hist
control FileStorageService as FS
database "Banco de Dados" as DB

Usuario -> FE : preencherFormDemanda(dados, oficio?)
activate FE
FE -> C : POST /demandas
activate C

C -> AuthZ : verificarPermissao("CRIAR_DEMANDA")
activate AuthZ
AuthZ --> C : permitido
deactivate AuthZ

C -> Val : validarCamposDemanda(dados)
activate Val
Val --> C : ok
deactivate Val

alt oficio informado
  C -> Val : validarArquivo(oficio)
  activate Val
  Val --> C : arquivoValido
  deactivate Val
end

C -> S : abrirDemanda(dados, usuario)
activate S
S -> City : find(cidade_id)
activate City
City -> DB : SELECT cidade
activate DB
DB --> City : registro
deactivate DB
City --> S : cidadeOuNull
deactivate City

alt cidade invalida
  S --> C : erro("Cidade invalida")
else cidade valida
  alt instituicao informada
    S -> Inst : find(instituicao_id)
    activate Inst
    Inst -> DB : SELECT instituicao
    activate DB
    DB --> Inst : registro
    deactivate DB
    Inst --> S : instOuNull
    deactivate Inst
  end

  alt oficio informado
    S -> FS : armazenar(oficio)
    activate FS
    FS --> S : metadadosDoOficio
    deactivate FS
  end

  S -> M : create(dados)
  activate M
  M -> DB : INSERT demanda
  activate DB
  DB --> M : demandaPersistida
  deactivate DB
  M --> S : demandaCriada
  deactivate M

  S -> Hist : registrar("Demanda criada")
  activate Hist
  Hist --> S : ok
  deactivate Hist

  S --> C : sucesso(demandaCriada)
end
deactivate S

C --> FE : resposta
deactivate C
FE --> Usuario : exibirResultado
deactivate FE
@enduml
