@startuml
skinparam linetype ortho
title Comunicação – UC04 Consultar Projetos de Lei

rectangle Usuario
rectangle Frontend
rectangle ProjetoLeiController
rectangle ProjetoLeiService
rectangle ProjetoLeiRepository

Usuario --> Frontend : 1: solicitarConsultaPL()
Frontend --> ProjetoLeiController : 2: GET /projetos-lei
ProjetoLeiController --> ProjetoLeiService : 3: consultarPLs()
ProjetoLeiService --> ProjetoLeiRepository : 4: listar()
ProjetoLeiRepository --> ProjetoLeiService : 5: listaPL
ProjetoLeiService --> ProjetoLeiController : 6: retornarResultados()
ProjetoLeiController --> Frontend : 7: resposta(lista)
Frontend --> Usuario : 8: exibirLista()

@enduml
