@startuml
skinparam linetype ortho
title Comunicação - UC07 Criar Alerta / Lembrete

rectangle Usuario
rectangle Frontend
rectangle AgendaReminderController
rectangle AgendaReminderService
rectangle EventRepository
rectangle EventAlertRepository
rectangle Queue
rectangle ProcessAgendaReminderJob
rectangle ChatbotNotificationClient
rectangle "Chatbot API" as ChatbotApi
rectangle "Servidor WebSocket" as WebSocket

Usuario --> Frontend : 1: escolherLembrete(eventoId, horario)
Frontend --> AgendaReminderController : 2: POST /agenda/reminders
AgendaReminderController --> AgendaReminderService : 3: createUserAlert(dados)

AgendaReminderService --> EventRepository : 4: buscarEvento(id)
EventRepository --> AgendaReminderService : 5: eventoOK
AgendaReminderService --> EventAlertRepository : 6: salvarLembrete()
EventAlertRepository --> AgendaReminderService : 7: alertaCriado
AgendaReminderService --> AgendaReminderController : 8: sucesso()
AgendaReminderController --> Frontend : 9: respostaOK()
Frontend --> Usuario : 10: mensagem()

Queue --> ProcessAgendaReminderJob : 11: processar quando devido
ProcessAgendaReminderJob --> ChatbotNotificationClient : 12: publishSystemAlert()
ChatbotNotificationClient --> ChatbotApi : 13: /internal/notifications/websocket-alert
ChatbotApi --> WebSocket : 14: publicar lembrete
@enduml
