@startuml
skinparam shadowing false
skinparam linetype ortho
skinparam RectangleBorderColor #333
skinparam RectangleBackgroundColor #F3F7FF
skinparam ArrowColor #444
title UC 05 - Cadastrar Liderança (Comunicação)

rectangle "Usuario" as User
rectangle "LiderancaController" as C
rectangle "LiderancaService" as S
database "LiderancaDB" as DB

left to right direction

User -down-> C : 1. Solicita "Cadastrar Liderança"
C -down-> S : 2. Executa lógica
S --> DB : 3. CRUD principal
DB --> S : 4. Resultado
S --> C : 5. Resposta
C --> User : 6. Sucesso


@enduml