@startuml
skinparam shadowing false
skinparam linetype ortho
skinparam RectangleBorderColor #333
skinparam RectangleBackgroundColor #F3F7FF
skinparam ArrowColor #444
title UC 33 - Cadastrar Evento (Comunicação)

rectangle "Usuario" as User
rectangle "AgendaEventoController" as C
rectangle "AgendaEventoService" as S
database "AgendaEventoDB" as DB
rectangle "DetectarConflitosService" as INC_DetectarConflitosService
rectangle "VincularContextoService" as EXT_VincularContextoService

left to right direction

User -down-> C : 1. Solicita "Cadastrar Evento"
C -down-> S : 2. Executa lógica
S --> INC_DetectarConflitosService : 3. Include DetectarConflitos
INC_DetectarConflitosService --> DB : 4. CRUD
DB --> INC_DetectarConflitosService : 5. Resultado
INC_DetectarConflitosService --> S : 6. Retorno
S --> DB : 7. CRUD principal
DB --> S : 8. Resultado
S --> EXT_VincularContextoService : 9. Extensão VincularContexto
EXT_VincularContextoService --> DB : 10. CRUD
DB --> EXT_VincularContextoService : 11. Resultado
EXT_VincularContextoService --> S : 12. Retorno
S --> C : 13. Resposta
C --> User : 14. Sucesso

note bottom of S
Includes: DetectarConflitos\nExtends: VincularContexto
end note

@enduml