@startuml
skinparam shadowing false
skinparam linetype ortho
skinparam RectangleBorderColor #333
skinparam RectangleBackgroundColor #F3F7FF
skinparam ArrowColor #444
title UC 35 - Criar Alerta/Lembrete (Comunicação)

rectangle "Usuario" as User
rectangle "AgendaAlertaController" as C
rectangle "AgendaAlertaService" as S
database "AgendaAlertaDB" as DB
rectangle "NotificacaoService" as INC_NotificacaoService

left to right direction

User -down-> C : 1. Solicita "Criar Alerta/Lembrete"
C -down-> S : 2. Executa lógica
S --> INC_NotificacaoService : 3. Include EnviarNotificacao
INC_NotificacaoService --> DB : 4. CRUD
DB --> INC_NotificacaoService : 5. Resultado
INC_NotificacaoService --> S : 6. Retorno
S --> DB : 7. CRUD principal
DB --> S : 8. Resultado
S --> C : 9. Resposta
C --> User : 10. Sucesso

note bottom of S
Includes: EnviarNotificacao
end note

@enduml